name = input("Please type a name: ")
currency = input("Please type a currency type such as dollars, nickles, peso, etc: ")
website = input("Please input a website where you can buy things: ")
seed_type = input("Please input a food that grows from seeds: ")
day_count = input("Input a number: ")
object_type = input("Input a thing: ")
size_type = input("Input a number: ")

print( name + " was down on his last two " + currency +".")
print("He saw a listing on " + website + " for some " + seed_type +" seeds.")
print("It took " + day_count +" days for the " + seed_type + " seeds to arrive and " + name + " planted them immediately.")
print("That night " + name +" dreamt the seeds grew into a " + object_type +".")
print("When " + name + " awoke the next morning, he was surprised to see his dream had come true.")
print("His " + seed_type + " seeds had grown into a " + size_type + " foot tall " + object_type +"!")